language: cpp

jobs:
    include:
        - os: linux
          dist: focal
          compiler: gcc

        - os: osx
          osx_image: xcode11.4  # -> macOS 10.15.4(see https://docs.travis-ci.com/user/reference/osx#macos-version)
          addons:
              homebrew:
                  packages:
                  - opencascade
                  - qt@5

before_install:
    - |
      case "${TRAVIS_OS_NAME}" in
      "linux")
          sudo apt-get -y install qtbase5-dev libqt5svg5-dev
          sudo apt-get -y install libocct-data-exchange-dev libocct-draw-dev
          ;;
#      "osx")
#          brew list opencascade
#          brew info opencascade
#          ;;
      esac

script:
    - chmod +x scripts/travis-build.sh
    - ./scripts/travis-build.sh
